### ISSUE TITLE
Support 'Lambert_Conformal_Conic_2SP'

### ISSUE THREAD

**Issue by darrenleeweber** [karimbahgat/PyCRS#37]
http://geotiff.maptools.org/proj_list/lambert_conic_conformal_2sp.html

An error related to this arose while trying to parse WKT, e.g.
http://spatialreference.org/ref/esri/102740/ogcwkt/

```
>>> pycrs.parse.from_esri_wkt(src.crs.to_wkt())
...
  File "/home/joe/miniconda3/envs/gis-dataprocessing/lib/python3.7/site-packages/pycrs/parse.py", line 303, in _parse_top
    raise NotImplementedError("Unsupported projection: The specified projection name %r could not be found in the list of supported projections" % projname)
NotImplementedError: Unsupported projection: The specified projection name 'Lambert_Conformal_Conic_2SP' could not be found in the list of supported projections
```

**Comment by darrenleeweber** [comment]
See also http://spatialreference.org/ref/epsg/2278/
```
>>> pycrs.parse.from_epsg_code(2278)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/joe/miniconda3/envs/gis-dataprocessing/lib/python3.7/site-packages/pycrs/parse.py", line 40, in from_epsg_code
    crs = from_proj4(proj4)
  File "/home/joe/miniconda3/envs/gis-dataprocessing/lib/python3.7/site-packages/pycrs/parse.py", line 696, in from_proj4
    unit.metermultiplier.value = partdict["+to_meter"]
AttributeError: 'Unknown' object has no attribute 'metermultiplier'
```

**Comment by karimbahgat** [comment]
Would be happy to add Lambert Conformal Conic 2SP as a supported projection. 

I don't have time to research this myself, but I could easily implement it if someone provides the **official name** for this projection in: 
- proj4
- ogc wkt
- esri wkt

And check if the projection has any wider implication, such as altering the values of other parameters. Here's a link that discusses the projection: 
https://trac.osgeo.org/gdal/ticket/5191
